include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - https://gitlab.com/hustle-ci/pipeline/raw/debian/salsa-ci.yml
  - https://gitlab.com/hustle-ci/pipeline/raw/debian/pipeline-jobs.yml

variables:
  RELEASE: 'unstable'
  SALSA_CI_DISABLE_APTLY: 'false'
