include:
  - https://gitlab.com/hustle-ci/pipeline/raw/master/salsa-ci.yml
  - https://gitlab.com/hustle-ci/pipeline/raw/master/pipeline-jobs.yml

variables:
  RELEASE: 'focal'
  SALSA_CI_AUTOPKGTEST_ARGS: '--timeout-install=7200'
  SALSA_CI_DISABLE_APTLY: 'false'

build source debug:
  extends: .build-source-only
  before_script:
    - set -x
    - env
    - (cd /usr/local/bin;
          patch < ${CI_PROJECT_DIR}/debian/patches/debug-install-deps.patch)
