include:
  - https://gitlab.com/hustle-ci/pipeline/raw/master/salsa-ci.yml
  - https://gitlab.com/hustle-ci/pipeline/raw/master/pipeline-jobs.yml

variables:
  RELEASE: 'focal'
  SALSA_CI_AUTOPKGTEST_ARGS: '--timeout-install=7200'
  SALSA_CI_DISABLE_APTLY: 'false'
